### ISSUE TITLE
New API: Query time range per JPX frame

### ISSUE THREAD

**Issue by deiruch** [Helioviewer-Project/api#1]
# Problem

Today clients can request image data/movies with a fixed cadence, and no more than 1000 frames at once. If certain images have been downloaded previously, clients still have to re-downloaded those images. New ways of temporal navigation (have a look at this chart: https://www.google.com/finance?q=msft ), caches, different error handling and other ideas for the next version of JHelioviewer mean that it would benefit greatly from more flexibility when requesting image data.
# Proposal

Add a new REST call to the existing [V2 API](http://api.helioviewer.org/docs/v2/):

```
GET /v2/getJPX2/?sourceId=14&linked=false&verbose=false&jpip=true
           &a=2015-01-01T00:00:00Z&a=2021-01-02T00:00:00Z&a=2014-05-07T00:00:00Z
           &b=2015-01-01T00:01:00Z&b=2021-01-02T00:01:00Z&b=2014-05-07T00:01:00Z
```

The API looks similar to the existing getJPX call, but instead of the `cadence`, `startTime` and `endTime` parameters it would allow the specification of a time range per frame. In addition to parameters `sourceId`, `linked`, `verbose`, `jpip` there are two new parameters `a` and `b`, repeated multiple times. The number of `a`'s and `b`'s must match.

For each pair `a`, `b` the server should search for a frame:
- If there are frames in the time range `a` (inclusive) to `b` (exclusive), it should return the frame which is closest to `(a+b)/2`.
- If there is no frame in the time range `a` (inclusive) to `b` (exclusive), it should return no frame.

The sample request above should return a movie with two frames from a minute after midnight of 2015-01-01, (no frame for 2021-01-02) and 2014-05-07.
# Use Cases
- If a user decides to switch the cadence from 30s to 20s, JHV can download a subset of required frames.
- If a download is corrupted halfway through, JHV can redownload corrupt frames.
- JHV can download solely non-cached frames.
# Notes

There are some things to consider when implementing the functionality:
- There is probably a better name than `getJPX2`
- GET requests are limited to 2048 length by some web proxies and browsers. This means approx. 40 frames can be requested with a single request. This is not an issue for JHV, but might cause inconvenience for other clients. Switching to Unix timestamps instead of ISO date/time strings would alleviate the problem (80 frames/request). Alternatively POSTing parameters might be a better solution.
- The suggested API is very close to the existing `getJPX` call to make implementation easier.

**Comment by wafels** [comment]
I can see how this might be useful for filling in gaps, for whatever reason they occur.  So you want to be able to get at most one frame within a specified timerange?  In the use cases, wouldn't this new API capability result in hundreds of requests for individual frames?
As for a name, how about getJP2ClosestToMidPoint ?

**Comment by deiruch** [comment]
* The API should return at most one frame PER PAIR OF A/B PARAMETERS
* JHV will probably eventually call the API for every 40 frames. Will that become an issue?
* `getJP2ClosestToMidPoint` is a fine name, except that it should return multiple frames (a `JPX`?). What about `getJPXClosestToMidPoint` ?

**Comment by wafels** [comment]
Ah, I misunderstood.  You want a JPX back consisting of very specific files within narrowly defined time ranges.  Ok.  Is there any advantage to this new API action having a single a and b parameter, something like....

a = [start_time_1, start_time_2,..., start_time_n]
b= [end_time_1, end_time_2,..., end_time_n]

Just wondering what would be better.  Any ideas?  Thanks!

**Comment by deiruch** [comment]
Comma separated dates would be fine as well! To me this makes no difference.

**Comment by samuelvonstachelski** [comment]
:+1:

**Comment by ddialer** [comment]
I uploaded new changes to the api.helioviewer.com with new API requested.

New API work the same way as requested.

```
GET /v2/getJPXClosestToMidPoint/?sourceId=14&linked=false&verbose=false&jpip=true
           &startTimes=1306886400,1306887000,1306887600
           &endTimes=1306886700,1306887300,1306887900
```

For the parameters names please use startTimes and endTimes. For the values use timestamps separated with the commas

And will update documentation for new getJPXClosestToMidPoint API usage shortly

**Comment by deiruch** [comment]
Great, exactly what I needed!

Sidenote: The "Request Parameters:" table in the doc is not quite correct, as it lists the regular time format instead of unix timestamps.

**Comment by dgarciabriseno** [comment]
Looks like this is already implemented on the main branch.
@wafels can we close this 5 years later :)

**Comment by bogdanni** [comment]
Note that JHV 4 (and its ancestor) does not use this API. It employs a persistent cache client-side.

**Comment by dgarciabriseno** [comment]
Noted.

**Comment by dgarciabriseno** [comment]
Closing as complete.
