### ISSUE TITLE
[Beta] HMI is missing data from around 20:17 to midnight. Images should be available

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#103]
Issue was raised [here](https://github.com/Helioviewer-Project/api/issues/97#issuecomment-1078455703)
This problem appears to be on beta's side since these images are available from SDO.
helioviewer.org isn't experiencing the same outage which is odd.
Need to figure out why these are missing.

**Comment by dgarciabriseno** [comment]
It looks like the downloader is a bit broken because HMI is queried at a 4 hour lag. Meaning at time T=0, HMI is being queried at time T-4 hours.

The beta server is downloading at a faster rate (every 3 minutes) than production (ever hour). So every day around midnight the query will search (for example) for time range 2022-03-25 00:00:00 - 2022-03-25 00:15:00

Now the bug is that because the requested time range is all on 03-25, it doesn't query lmsal/jsoc for the date 3/24. So it's looking for HMI images at T-4 (2022-03-24 20:00:00 - 20:15:00) but the data it's actually searching is on 03-25.

**Comment by helioshk** [comment]
Thank you!
