### ISSUE TITLE
In GSFC has data but in IAS no. Days now

### ISSUE THREAD

**Issue by Anthrwpos** [Helioviewer-Project/api#144]
Hi, in GSFC has data but in IAS no. Days now. Can  be fixed this? Thanks

**Comment by bogdanni** [comment]
Please report data issues to the server side. Transferring.

**Comment by ebuchlin** [comment]
Thanks for the report. Indeed the default Python version of the system had changed, and this crashed the download scripts (still Python2). Now Python2 is called, and the data are back.
