### ISSUE TITLE
Solar Orbiter EUI JPEG2000 files are now available

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#149]
Solar Orbiter EUI data JPEG2000 files are now available. I heard yesterday that they are being copied into the Solar Orbiter servers at the SDAC. These images are already available via JHelioviewer if you point it to the right server. They should also be made available via helioviewer.org.

Solar Orbiter orbits around the Sun at highly variable distances, and takes images of the Sun from very different points of view compared to viewing from the Earth. At the moment, overplots of EUI data with other datasets will not be physically meaningful because of the differing points of view. This is the same situation we are in when it comes to STEREO data - therefore we will be relying on the user to understand what they are doing when they select EUI data.

In order to use these images we should copy them from the SDAC onto the helioviewer servers - this is a new server description in the downloader. Then, we'll have to update the backend to properly incorporate the new data. I think the front end may need to be updated to allow the new data to be selectable. All this should be done on the beta server first.  I anticipate some changes on the plotting calculation on the front end to accommodate the EUI data.

Solar Orbiter also makes the case that work on re-projecting images from arbitrary locations needs to be accomplished.

**Comment by wafels** [comment]
Instrument paper at https://www.aanda.org/articles/aa/full_html/2020/10/aa36663-19/aa36663-19.html

**Comment by bogdanni** [comment]
Original location of files at https://www.sidc.be/EUI/data/releases/202204_release_5.0/L3/

**Comment by wafels** [comment]
The file path implies other releases - is that anticipated?

**Comment by bogdanni** [comment]
This is the latest release. Until now each subsequent release overwrote the previous, i.e., file names could change due to new calibration version.

I dealt with this on the ROB server by dropping all files from a previous release and reinserting all from the new release.
The releases were infrequent, but going forward we can expect files being made public in the interval between releases. I expect also that the names of older files to stabilize.

**Comment by dgarciabriseno** [comment]
@wafels Do you know where we get the color table png for this or how they're generated?

The other ones live here https://github.com/Helioviewer-Project/api/tree/master/docroot/resources/images/color-tables

**Comment by bogdanni** [comment]
FSI,HRI 171 = AIA 171
FSi 304 = AIA 304
HRI LYA, see attached

[HRILYA-color.txt](https://github.com/Helioviewer-Project/api/files/8969516/HRILYA-color.txt)

**Comment by bogdanni** [comment]
Right.

**Comment by wafels** [comment]
The Angstrom symbol is in the description on hv.org

![Screen Shot 2022-07-01 at 11 13 07](https://user-images.githubusercontent.com/983575/176921962-38aa802c-f393-439f-a949-d40a68d7f433.png)

which is not properly displayed when you press the "H" (meaning header) button in the image selector

![Screen Shot 2022-07-01 at 11 12 18](https://user-images.githubusercontent.com/983575/176922142-82833ff1-f2a9-4d8f-b53e-e626609eaebd.png)

Note that AIA 304 does not have an angstrom symbol attached. I think the Angstrom symbol can be dropped with no difficulty.
