### ISSUE TITLE
getMovieStatus progress resets after reaching 100%

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#161]
Progress while movie is building:
```
{"status":1,"statusLabel":"Processing","currentFrame":7,"numFrames":100,"progress":0.07,"queuePosition":0}
```

Progress when 100% is reached, before the final movie is created
```
{"status":1,"statusLabel":"Processing","currentFrame":null,"numFrames":100,"progress":0,"queuePosition":0}
```

Final result
```
{"frameRate":1.0101,"numFrames":100,"startDate":"2022-06-09 06:13:09","status":2,"endDate":"2022-07-11 10:16:57","width":1440,"height":820,"title":"SOHO LASCO C3 white-light, SOHO LASCO C2 white-light, SDO AIA 171 (2022-06-09 06:13:09 - 2022-07-11 10:16:57 UTC)","thumbnails":{"icon":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/preview-icon.png","small":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/preview-small.png","medium":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/preview-medium.png","large":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/preview-large.png","full":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/preview-full.png"},"url":"https:\/\/api.helioviewer.org\/cache\/movies\/2022\/07\/09\/gjKN5\/2022_06_09_06_13_09_2022_07_11_10_16_57_LASCO_C3__LASCO_C2__AIA_171.mp4","statusLabel":"Completed"}
```

**Comment by wafels** [comment]
What do the first two JSON outputs refer to? Is it the frame creation process?

**Comment by wafels** [comment]
So how is the end of the frame creation flagged? Seems like that should be noted explicitly somewhere.

**Comment by wafels** [comment]
That seems like a bug waiting to happen. Should there be a separate "FrameBuildComplete" flag. It's set to true when all the frames are completed.

**Comment by dgarciabriseno** [comment]
No, I think progress should go all the way up to 90% and then stay there until it's done.
We don't have any information to track the finalization part, creating the video after all the frames have been processed. So rather than resetting to 0, I think it should count its way up to 90% and then stay there until it's done.

You should never see 100%. 100% means it would be done and there wouldn't be a progress bar anymore.
