### ISSUE TITLE
TRACE images are not being ingested in to database

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#17]
TRACE images are not being injected into the image database.  The failure occurs when the downloader attempts to validate the parameter data.  Since the downloader relies on SunPy v0.2, and SunPy v0.2 does not know about TRACE images, the downloader validator fails.

Two possible solutions:
(1) Update SunPy 0.2 to include TRACE data
(2) Update the downloader code to use the latest stable version of SunPy (0.6.something at time of writing).

Option (1) means carrying on with a very outdated version of SunPy, and carrying that code onwards. Option (2) requires a lot more development up front, but would take advantage of the increasing stability of the Map object in SunPy.

Option (2) is preferred going forward, with the proviso that Option (2) means understanding and maintaining SunPy's interaction with JP2 files as mediated by Glymur and OpenJPEG.

**Comment by bogdanni** [comment]
Maybe hvJP2K can help? We are running the entire server infrastructure on it.

**Comment by wafels** [comment]
That's interesting - how do you use it?

**Comment by wafels** [comment]
Fixed by upgrading ingestion script. Also, SunPy 0.7 is also used.
