### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#18]
Which version of the API is the statistics page using?

**Comment by ddialer** [comment]
Statistic using v2 API

**Comment by dmueller3000** [comment]
Would it also be possible to have a page showing the results for v1 API, in particular for JPX movies? Right now, only the beta version of JHV 3.0 is using v2, while all other JHV versions are still using v1 at this point.

**Comment by wafels** [comment]
I agree - it would be good to break the stats down by API usage.

**Comment by ddialer** [comment]
sure you can. just use http://legacy.helioviewer.org/statistics/ for API v1

**Comment by bogdanni** [comment]
SWHV (that is JHV 2.10) always sets the user agent to something like "JHV/SWHV-2.10.0.6838M" (version, commit number). I have the impression that no other versions of JHV set the user agent.

**Comment by bogdanni** [comment]
Made a commit to JHV-SWHV for more info, on my computer it gives now:
JHV/SWHV-2.10.0.6839M (x86_64 Mac OS X 10.11.4) Oracle Corporation JRE 1.8.0_77

**Comment by dgarciabriseno** [comment]
http://legacy.helioviewer.org/statistics/ is gone.
Do we will still need the v1 API stats, or is it old enough that we can leave it alone?

**Comment by wafels** [comment]
What do you mean? We need the records and the ability to generate summary
statistics.

**Comment by dgarciabriseno** [comment]
I mean the **legacy** version is gone. It just redirects to the current API statistics.

**Comment by dgarciabriseno** [comment]
Discussed this with @wafels, decided we can close this since it was created back during the transition from v1 to v2 for JHV. All requests should now be using the v2 API.
