### ISSUE TITLE
Old HMI continuum image can't be loaded

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#194]
Specifically time `2010-12-06 18:45:26` for HMI continuum

Currently debugging. The error from the back end is `{"error":"Invalid image geometry","errno":1}`
I suspect this is coming from image magick, but when downloading the jp2 file it is displayed fine.

**Comment by bogdanni** [comment]
`DSUN_OBS` is broken for the sequence, values like -7839761.0, -2.5358362e+28, etc.

**Comment by dgarciabriseno** [comment]
Yes, that's the problem. Any idea how I work around it? Fake it? put in a known good value?

**Comment by wafels** [comment]
Probably best to remake the JP2 image.

**Comment by dgarciabriseno** [comment]
Thoughts on #195? 3 line workaround. If the image scale is unexpectedly low, then override it back to 0.6.
This seems to work for my local copy of helioviewer. I have a query running on the database to look for these bad image scales and then I can fine tune the value to check.

**Comment by bogdanni** [comment]
How did you choose the threshold?
EUI HRI has CDELT = 0.492 (arcsec/pixel) and goes down to ~0.3 au, I think it will hit the threshold.

**Comment by dgarciabriseno** [comment]
I chose the threshold using the highest invalid value I could find in the database.
EUI HRI actually results in a scale around 0.159362 which is just above the threshold.

**Comment by bogdanni** [comment]
The closest approach of Solar Orbiter will be 0.28au. If I understand correctly the calculation which is done, it will result in a value of 0.1378 and this threshold will be breached.

**Comment by dgarciabriseno** [comment]
Ok, let me think of something else.

**Comment by dgarciabriseno** [comment]
Since we compute the scale along with some other metadata and store them in the database, there's no reason for PHP to calculate them. Right now it does, and that was the only thing stopping me from simply overriding the scale value in the database.

I can remove that redundant PHP code so that the values in the database are used instead of read from the file.
Then keep a sql query in the repository that patches the scale for the broken files.

This would be a good solution since it removes some duplicate code and fixes the specific broken files without making any assumptions about other images. And I already have a list of the files to patch.

**Comment by bogdanni** [comment]
In general, you can reject any DSUN lower than 4% of au, there will probably be no imagers so close to the Sun in our lifetime. I doubt that PSP/WISPR images at perihelion (and it does not even look at the Sun).
But Jack is right, the metadata should be corrected, such old data should be mature now.

**Comment by dgarciabriseno** [comment]
Ok, I'll use 4% as the threshold for now.
Who do we contact to get the metadata fixed?

**Comment by dgarciabriseno** [comment]
Merged this in.
