### ISSUE TITLE
Check for the presence of JP2 images if they are in the database

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#21]
The image database tracks the images available.  There should be a method to check that images that the database claims are there are actually present on the system.

**Comment by dgarciabriseno** [comment]
The script from the PR is running. It will take a while. If it doesn't run into any issues I'll merge it in once it is complete.

**Comment by bogdanni** [comment]
Would be nice if it would be possible to check current files against stored checksums, i.e., catch files silently corrupted by storage failures.

**Comment by dgarciabriseno** [comment]
That would be nice. I'll see if I can adapt this to also do that.
It will be a separate option since that would take much longer than just checking that the file exists.

**Comment by dgarciabriseno** [comment]
It does not appear that we have stored checksums... so this may not be possible yet.
