### ISSUE TITLE
Change the expected delay for XRT data in the status page.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#23]
The helioviewer.org data acquisition status page now includes XRT data.  According to XRT data experts, the expected time lag between real time and data availability is three weeks.  The time lag on the status page should be updated to reflect that.  So if the time lag is three weeks, then XRT data should appear green. If the lag is 3-4 weeks, yellow; 4-5 weeks, orange; >5 weeks, red.

**Comment by ddialer** [comment]
Changed XRT data status page. Also added redirect from helioviewer.org to api.helioviewer.org for status, coverage and statistics pages

**Comment by wafels** [comment]
confirmed
