### ISSUE TITLE
Bokeh charts don't include more recent data sources

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#240]
Since the bokeh charts ([api.helioviewer.org/statistics/bokeh](https://api.helioviewer.org/statistics/bokeh))  were first created, new data sources have been added, for example, SUVI. The bokeh charts have not been updated to reflect this.

The bokeh charts should probably first find out what data sources are available, and then create statistics per data source as appropriate. This would enable the charts to stay up-to-date with data sources as they are added. See also #83.

**Comment by dgarciabriseno** [comment]
The charts exist, but there's no links to them yet.
