### ISSUE TITLE
No new SDO data after 21-Jan-23 13:37

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#247]
There are no new SDO images available on any server.
On sdo.gsfc.nasa.gov they are up to date.

**Comment by helioshk** [comment]
resolved

**Comment by dgarciabriseno** [comment]
This may have just been a hiccup upstream. I didn't change anything.

Also you can take a look at this https://api.helioviewer.org/status.xml 
It's an RSS feed which reports when different sources start falling behind schedule https://api.helioviewer.org/status.xml

**Comment by dgarciabriseno** [comment]
If data isn't showing up and it wasn't flagged in the feed then it's useful to know.
