### ISSUE TITLE
SDO data stuck on 2023-03-24

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#276]
Could you please contact the right people to get it going again? Thanks.

**Comment by dangarbri** [comment]
@wafels Reached out to the right people this morning. Hopefully it's resolved soon.

**Comment by wafels** [comment]
The original issue on 2023-03-24 was upstream of GSFC. Processing has re-started at the upstream source, but there are significant gaps in the coverage on all days between 2023-03-24 and the time of writing (2023-03-29). The upstream source has been notified.

**Comment by wafels** [comment]
AIA 171 looks like it is back to nominal operations, but the other channels are still behind.

**Comment by wafels** [comment]
All AIA and HMI channels are back to near real time. Closing.
