### ISSUE TITLE
 'autocommit' invalid keyword  for adaptor.connect() 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/api#28]
running python install.py I ve got 
<pre>
ERROR: TypeError: 'autocommit' is an invalid keyword argument for this function [MySQLdb.connections]
TypeError: 'autocommit' is an invalid keyword argument for this function
Traceback (most recent call last):
  File "/var/www/helioviewer/install/helioviewer/installer/gui.py", line 124, in process_images
    db, cursor = setup_database_schema(admin, adminpass, "localhost",  hvdb, hvuser, hvpass, mysql)
  File "/var/www/helioviewer/install/helioviewer/db.py", line 23, in setup_database_schema
    create_db(adminuser, adminpass, dbhost, dbname, dbuser, dbpass, mysql, adaptor)
  File "/var/www/helioviewer/install/helioviewer/db.py", line 100, in create_db
    db = adaptor.connect(autocommit= True, use_unicode=True, charset="utf8", host=dbhost, user=adminuser, passwd=adminpass)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 187, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
TypeError: 'autocommit' is an invalid keyword argument for this function
root@dev-helioviewer:/var/www/helioviewer/install# vi /var/www/helioviewer/install/helioviewer/db.py 
</pre>

Workaround found :
remove autocommit= True in  adaptor.connect() line 100 of /var/www/helioviewer/install/helioviewer/db.py 

Best regards
Pablo

**Comment by dgarciabriseno** [comment]
autocommit=True is currently supported. I recently made some updates to db.py when I set up my development environment. Since this is an old issue and I can't reproduce it, I'm going to close it.
Please open a new issue if you find any other problems with the database setup.
