### ISSUE TITLE
Notifications of lagging data acquistion at GSFC.

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#29]
It would be good if I got emails when there is an issue with any our image streams.  Any time a data source crosses the "lagging a lot" threshold I should get an email.

**Comment by dgarciabriseno** [comment]
No email notification yet, but I found that there was a broken, undocumented API call called getStatus.
See here: https://api.helioviewer.org/v2/getStatus/ 
We can leverage this to script something that will notify us if any of the lagging times get too large.

**Comment by dgarciabriseno** [comment]
I have been thinking about this one lately and decided that it would be nice to use an RSS feed so anyone can subscribe to status alerts. Also because it seems like we don't have email capabilities on our server.

**Comment by dgarciabriseno** [comment]
The first iteration of this has been implemented in 36623121774e77b3b69712b8cfeea62f051b72ab 
It's live on beta and prod. For now we'll keep it just here to see how well it works and make a blog post about it later if it behaves well.
