### ISSUE TITLE
Version 2 doesn't always return files

### ISSUE THREAD

**Issue by wtthompson** [Helioviewer-Project/api#3]
These two requests only differ by one second, but one returns a result and the other doesn't.

IDL> hv_get,'2015-03-31T23:59:59',10,/verbose
% SOCK_GET_MAIN: 1077997 bytes of 2015_03_31__23_59_47_35__SDO_AIA_AIA_171.jp2 copied in 0.06 seconds.
IDL> hv_get,'2015-04-01T00:00:00',10,/verbose
% SOCK_GET_MAIN: http://api.helioviewer.org/v2/getJP2Image/?date=2015-04-01T00:00:00.000Z&sourceId=10 not found on server.

**Comment by dzarro** [comment]
IDL is reporting what it senses in the server header response. Entering the following in a browser:

http://api.helioviewer.org/v2/getClosestImage/?date=2015-04-01T00:00:00.000Z&sourceId=10

returns:

{"error":"Unable to process XML Header for \/var\/www-dev\/api\/docroot\/jp2\/AIA\/2015\/04\/01\/171\/2015_04_01__00_00_11_34__SDO_AIA_AIA_171.jp2: File does not exist.  Check cache directory permissions.","errno":13}

Same thing happens with V1.

**Comment by wafels** [comment]
Closed since we are now using the complete image database on the new server.
