### ISSUE TITLE
db.py definition is obsolete

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/api#30]
Hello, 

In db.py the definition of the table is obsolete .

from log
<pre>
====[DATE]====================

2017/06/28 08:55:33

====[SOURCE]==================

inf-helio-test-api.ias.u-psud.fr/?action=getDataSources

====[MESSAGE]=================

Error executing database query (SELECT s.name AS nickname, s.id AS id, s.enabled AS enabled, s.layeringOrder AS layeringOrder, s.units AS units, a.name AS a_name, a.description AS a_description, a.label AS a_label, b.name AS b_name, b.description AS b_description, b.label AS b_label, c.name AS c_name, c.description AS c_description, c.label AS c_label, d.name AS d_name, d.description AS d_description, d.label AS d_label, e.name AS e_name, e.description AS e_description, e.label AS e_label FROM datasources s LEFT JOIN datasource_property a ON s.id=a.sourceId AND a.uiOrder=1 LEFT JOIN datasource_property b ON s.id=b.sourceId AND b.uiOrder=2 LEFT JOIN datasource_property c ON s.id=c.sourceId AND c.uiOrder=3 LEFT JOIN datasource_property d ON s.id=d.sourceId AND d.uiOrder=4 LEFT JOIN datasource_property e ON s.id=e.sourceId AND e.uiOrder=5  ORDER BY s.displayOrder ASC, a.name ASC;): Unknown column 's.displayOrder' in 'order clause'

====[POST]=================

'action' => getDataSources

inf-helio-test-api.ias.u-psud.fr/?action=getDataSources
</pre>

Indeed 
<pre>
def create_datasource_table(cursor):
    """Creates a table with the known datasources"""
    cursor.execute("""
    CREATE TABLE `datasources` (
      `id`            smallint(5) unsigned NOT NULL,
      `name`          varchar(127) NOT NULL,
      `description`   varchar(255) DEFAULT NULL,
      `units`         varchar(20) DEFAULT NULL,
      `layeringOrder` tinyint(3) unsigned NOT NULL,
      `enabled`       tinyint(1) unsigned NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;""")
</pre>

although in obelix.sql provided by Serge 
<pre>
CREATE TABLE `datasources` (
  `id` smallint(5) UNSIGNED NOT NULL,
  `name` varchar(127) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `units` varchar(20) DEFAULT NULL,
  `layeringOrder` tinyint(3) UNSIGNED NOT NULL,
  `enabled` tinyint(1) UNSIGNED NOT NULL,
  `sourceIdGroup` varchar(256) DEFAULT '',
  `displayOrder` tinyint(2) NOT NULL DEFAULT '0',
  `groupOne` int(11) DEFAULT '0',
  `groupTwo` int(11) NOT NULL DEFAULT '0',
  `groupThree` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
</pre>

Best regards, 
Pablo 
IAS

**Comment by ddialer** [comment]
Pablo,
I just updated https://github.com/Helioviewer-Project/api/blob/master/install/helioviewer/db.py with new mysql scheme. Could you try install with new db.py file

**Comment by MedocIAS** [comment]
Problem solved
