### ISSUE TITLE
Model numbering in DONKI CME

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#306]
The attached screenshot shows the issue - the tab "Model 1" is repeated. Don't know if this is a bug or a true representation of the contents of the API request. If you click on the tab the contents are different.

<img width="778" alt="Screen Shot 2023-04-27 at 12 05 12" src="https://user-images.githubusercontent.com/983575/234922043-aef22777-1c53-456e-a738-549c22766711.png">

**Comment by dgarciabriseno** [comment]
This is my fault.
The models are associated with a CME Analysis. So The first model 1 is for Analysis 1. And the second "Model 1" is for Analysis 2.
I can't think of a good way to express this in the tab names. Maybe "Model 1-1" and "Model 2-1"?

**Comment by wafels** [comment]
Can an analysis have multiple models? Could there be a Model 1-1, Model 1-2,...., Model 1-n ?

**Comment by wafels** [comment]
So "Model 1-1" and "Model 2-1" make sense, but they are hard to understand. What about "Analysis 1" and "Model 1-a", "Model 1-b", "Model 1-c",... or maybe the other way around?

**Comment by dgarciabriseno** [comment]
I'm going to see if I can get it to do this. So that it's visually clear the model is associated with the analysis

![image](https://user-images.githubusercontent.com/94071409/235198103-a45b19a5-c14a-406a-b25a-c06b9239b17f.png)

**Comment by dgarciabriseno** [comment]
This is up on beta, take a look

**Comment by dgarciabriseno** [comment]
Closing. The UI has been updated to visually link analyses and models. I think this is sufficient for the duplicate numbering.
