### ISSUE TITLE
Non-standard PIN label for DONKI CME

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#307]
The attached screenshot shows the generated pin label for a DONKI CME notification - it is a time, and lacks the information present in other DONKI CME pin labels.

<img width="1498" alt="Screen Shot 2023-04-27 at 12 05 27" src="https://user-images.githubusercontent.com/983575/234923779-6c389c14-9e37-481d-9409-7adb34aaaf91.png">

**Comment by dgarciabriseno** [comment]
The lack of information is due to actual lack of information.

It shows no detailed information because at the time it was loaded, there was no analysis information.

**Comment by wafels** [comment]
Ok, so working as expected!
