### ISSUE TITLE
Update LinkShortener.php to use a hash instead of random numbers

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#308]
By using a hash instead of random numbers, the same long url will return the same short url.

This is the function that should be updated to accept the longUrl as an input, and return a hash.
https://github.com/Helioviewer-Project/api/blob/99298eac074634960e07062cc268d8b6896a36d3/src/Net/LinkShortener.php#L16

**Comment by prabhjotsingh18** [comment]
Hey @dgarciabriseno , I can take this issue. 
just to confirm the changes

1. make the function `GenerateShortString()` accept longurl as args and then return a random hash 
2. make changes to the `public static function Create(string $longUrl): string ` as well.

**Comment by dgarciabriseno** [comment]
@prabhjotsingh18, thanks for your interest, the issue is still open and you can work on it.

For the changes
1. The hash returned shouldn't be random, it should return a hash of `$longUrl`
2. Yes, all calls to `GenerateShortString` need to be updated.

**Comment by dgarciabriseno** [comment]
Thanks!
