### ISSUE TITLE
Helioviewer SunPy client get_closest_image test fails

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#31]
The SunPy client get_closest_image test fails

https://github.com/sunpy/sunpy/blob/master/sunpy/net/tests/test_helioviewer.py#L38

with the failure

HTTPError: HTTP Error 500: Internal Server Error

Did something change online?

**Comment by ddialer** [comment]
Fixed. The issue was related to JP2 image XML reader and was giving "Uncaught Error: Class 'DOMDocument' not found" error.

**Comment by ddialer** [comment]
And SunPy test is using legacy.helioviewer.org this is why we received this error.
