### ISSUE TITLE
GSFC beta: Connection refused

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#311]
GSFC beta has been unreachable for a while:
java.net.ConnectException: Connection refused: jpips://beta.helioviewer.org:8092/movies/SDO_AIA_304_F2023-05-16T16.04.39.500Z_T2023-05-16T17.04.39.500ZB60L.jpx

**Comment by dgarciabriseno** [comment]
Apologies, a service wasn't running on beta that should have been. It should be accessible now.

Also, please make sure you're using the latest version of JHelioviewer to support the jpips protocol.

**Comment by helioshk** [comment]
@dgarciabriseno
SDO doesn't seem to be getting new images since yesterday morning on GSFC beta.
