### ISSUE TITLE
ROB Data Sources Status Page

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#316]
Minor, but please update with correct capitalization https://api.helioviewer.org/status/:
EUI -> Source `ROB EUI`
SUVI -> Source `ROB JHV`
SWAP -> Source `ROB PROBA2`

**Comment by dgarciabriseno** [comment]
Do you have a link I can add for SUVI -> Source ROB JHV?
The source are links to the mission pages.

EUI links to https://www.sidc.be/EUI/intro
and SWAP links to https://proba2.sidc.be/

**Comment by bogdanni** [comment]
Link word: 
ROB to http://swhv.oma.be
SUVI to https://www.ncei.noaa.gov/products/goes-r-solar-ultraviolet-imagers-suvi
(I think that's the correct one, but I'm not versed in the departments of US agencies)

**Comment by dgarciabriseno** [comment]
> SUVI -> Source `ROB JHV`

Should this be SUVI -> Source `ROB SUVI`

**Comment by bogdanni** [comment]
Yes, meant to say that. Better have it  `ROB / SUVI`

**Comment by dgarciabriseno** [comment]
Does it look good here?
https://api.beta.helioviewer.org/status/

**Comment by bogdanni** [comment]
For PROBA2 and EUI please link only to the project page (like it was), the data is self-produced by each project.  Behind the scenes I'm still involved, of course :)

**Comment by dgarciabriseno** [comment]
Okay, so you'd like for only "ROB SUVI" to link to both, and the others should just link to the project pages?

**Comment by dgarciabriseno** [comment]
Check https://api.beta.helioviewer.org/status/ again now

**Comment by bogdanni** [comment]
Perfect, thanks!
