### ISSUE TITLE
HEK infos 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/api#32]
Hello, 
our test install at IAS,  https://inf-helio-test.ias.u-psud.fr, is almost ok but the HEK is missing  

sql log shows that a request is made on 'events' table
<pre>
1988 Connect    production@localhost on
1988 Init DB    HelioV
1988 Query    SET @@session.time_zone = '+00:00'
1988 Query    SELECT * FROM events WHERE '2017-06-29 23:59:53' BETWEEN event_starttime AND event_endtime ORDER BY event_starttime
1988 Quit   
</pre>

But checking the 'events' table I ve got nothing in it
<pre>
mysql> select * from events
    -> ;
Empty set (0.00 sec)

mysql>
</pre>

How can get the HEK infos ?

Best regards,
Pablo
IAS

**Comment by ddialer** [comment]
@MedocIAS, 

To answer your question there is two ways to display events. First there is setting on config file (/settings/config.ini) named “db_events”:
```
[events]
;Use MySQL database to store events (true = yes; false = no)
db_events = true
```

If db_events is disabled then all events will be loaded straight from LMSAL database and generate all regions on the fly. Also you will not be able to use Events Timeline and you will have to hide “Events Timeline” tab in index.php file.

And if you enable db_events then you need to setup extra CRON job to load events into helioviewer database and CRON job to generate “Events Timeline” data coverage. Here how this cron jobs looks like:
```
# Data Coverage
*/5  * * * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=updateDataCoverage&period=7D" 1>> /dev/null 2>&1

# Import Events
0 * * * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=importEvents&period=1D" 1>> /dev/null 2>&1
0 0 * * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=importEvents&period=7D" 1>> /dev/null 2>&1
0 0 1 * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=importEvents&period=31D" 1>> /dev/null 2>&1
```

**Comment by MedocIAS** [comment]
Hello, 

ImportEvents & updateDataCoverage are KO on our side 
In my Config.ini I have 
<pre>
db_events = true
</pre>


As suggested, I put the following in my crontab for testing purpose this morning.

<pre>
# Data Coverage
*/5  * * * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=updateDataCoverage&period=7D" 1>> /dev/null 2>&1

# Import Events
0 * * * * /usr/bin/wget -qO /dev/null "https://api.helioviewer.org/?action=importEvents&period=1D" 1>> /dev/null 2>&1

</pre>

It did not have any effect apparently.
Indeed, checking the DB after several days I didn't find anything in the tables events or events_coverage.

<pre>
mysql> select * from events_coverage ;
Empty set (0.00 sec)

mysql> select * from events ;
Empty set (0.01 sec)

mysql>

</pre>

So I check from a command line

<pre>
 wget "https://api.helioviewer.org/?action=importEvents&period=1D"

--2017-09-11 18:44:56--  https://api.helioviewer.org/?action=importEvents&period=1D
Résolution de api.helioviewer.org (api.helioviewer.org)… 129.164.137.18
Connexion à api.helioviewer.org (api.helioviewer.org)|129.164.137.18|:443… connecté.
requête HTTP transmise, en attente de la réponse… 200 OK
Taille : 26 [application/json]
Enregistre : «index.html?action=importEvents&period=1D.1»

index.html?action=importEvents&period=1D.1           100%[===================================================================================================================>]      26  --.-KB/s    in 0s     

2017-09-11 18:45:09 (1,51 MB/s) - «index.html?action=importEvents&period=1D.1» enregistré [26/26]

Inside the result file I ve found :

"{\"status\":\"success\"}"

</pre>


Maybe I missed something, do you have an idea ?

**Comment by ddialer** [comment]
@MedocIAS, please change https://api.helioviewer.org to your own server:
something like this:
```
# Data Coverage
*/5  * * * * /usr/bin/wget -qO /dev/null "https://inf-helio-test-api.ias.u-psud.fr/?action=updateDataCoverage&period=7D" 1>> /dev/null 2>&1

# Import Events
0 * * * * /usr/bin/wget -qO /dev/null "https://inf-helio-test-api.ias.u-psud.fr/?action=importEvents&period=1D" 1>> /dev/null 2>&1

```

**Comment by MedocIAS** [comment]
It works 
Thank you !
