### ISSUE TITLE
Discordant STA/COR2 image between GSFC and IAS servers 

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#325]
At least this image with `DATE_OBS = 2022-05-21T00:23:30.011`  is different between GSFC & IAS server, possibly the metadata.
As far as I see, the file from IAS has all s/c position keywords set to 0. Probably the file from GSFC was reprocessed, but the update was not propagated to IAS.

File from IAS: `JP2 file created locally at NASA-GSFC using HV_WRITE_JP2_LWG at Mon May 23 13:59:37 2022`
File from GSFC: `JP2 file created locally at NASA-GSFC using HV_WRITE_JP2_LWG at Wed Jun 22 15:45:56 2022.`

**Comment by bogdanni** [comment]
Same issue for STA/EUVI 304 with `DATE_OBS = 2022-05-20T16:00:45.010`

**Comment by dgarciabriseno** [comment]
I can't find a record of these being reprocessed, but it seems like they must have been. I haven't been logging when data is reprocessed, but this seems like information that should be kept somewhere order to keep the mirrors relatively in sync.

**Comment by bogdanni** [comment]
My idea is to have insertion time as a column in the HV database and add the ability to query that remotely (HAPI?)

**Comment by dgarciabriseno** [comment]
The date range where the files are different for stereo-A are:
2022-05-17 00:00:00 To 2022-05-21 23:59:59

Having the insertion time in the database seems like a good record keeping step for other reasons, but I don't think it solves this. I don't just want a list of when something was added, I want to know when something was replaced.

Maybe a web page around HV's status page with a list like:
- STEREO-A 2022-05-17 00:00:00 To 2022-05-21 23:59:59 reprocessed and reimported on date ABC

**Comment by dgarciabriseno** [comment]
Another case is that these images will likely be replaced: https://api.helioviewer.org/v2/goto/?id=02a3a12bee4a49e8

**Comment by bogdanni** [comment]
I think it solves the issue if the sync process is not a dumb download of files from the past 2 or so days but a query on files inserted after the last run of the script, followed by download of that list.

**Comment by dgarciabriseno** [comment]
That would be a better download process.
We would need data providers to release their data that way for it to work.

**Comment by bogdanni** [comment]
At least the sync between the HV servers which use the same software would work better.

**Comment by dgarciabriseno** [comment]
Noted. I have it as a TODO. It would make a better sync mechanism.

For now I emailed the IAS maintainers about re-importing this section.

**Comment by dgarciabriseno** [comment]
This section of data was re-imported on the IAS server and the data matches now.
