### ISSUE TITLE
Update movie on youTube 

### ISSUE THREAD

**Issue by MedocIAS** [Helioviewer-Project/api#33]
Hello, 

Trying to upload a movie to youTube on inf-helio-test.ias.u-psud.fr I have an error in apache :

<pre>
[Thu Sep 14 15:55:06.746598 2017] [:error] [pid 27848] [client 129.175.64.204:36826] PHP Warning:  include_once(GoogleSDK/src/Google/autoload.php): failed to open stream: No such file or directory in /var/www/api/src/Movie/YouTube.php on line 32, referer: https://inf-helio-test.ias.u-psud.fr/
[Thu Sep 14 15:55:06.746719 2017] [:error] [pid 27848] [client 129.175.64.204:36826] PHP Warning:  include_once(): Failed opening 'GoogleSDK/src/Google/autoload.php' for inclusion (include_path='.:/usr/share/php:/usr/local/ZendFramework-2.4.13/library') in /var/www/api/src/Movie/YouTube.php on line 32, referer: https://inf-helio-test.ias.u-psud.fr/
[Thu Sep 14 15:55:06.747412 2017] [:error] [pid 27848] [client 129.175.64.204:36826] PHP Fatal error:  Class 'Google_Client' not found in /var/www/api/src/Movie/YouTube.php on line 49, referer: https://inf-helio-test.ias.u-psud.fr/
[Thu Sep 14 15:55:06.747518 2017] [:error] [pid 27848] [client 129.175.64.204:36826] PHP Fatal error:  Call to a member function getCode() on array in /var/www/api/docroot/index.php on line 207, referer: https://inf-helio-test.ias.u-psud.fr/
</pre>

It seems that the file GoogleSDK/src/Google/autoload.php is required but I don' have a GoogleSDK dir and i cannot find it on git repository 

I did install php-google-api-php-client but couldn't find autoload.php
<pre>
root@inf-helio-test:/var/www/api# dpkg -L php-google-api-php-client |grep autoload.php
</pre>
So I installed ZendFramework-2.4.13 and add the directory /usr/local/ZendFramework-2.4.13/library in my php.ini ( include_path section )...
I have found a autoload.php file in it but the upload still fails 
<pre>
root@inf-helio-test:/var/www/api# locate autoload.php 
/usr/local/ZendFramework-2.4.13/library/Zend/Session/compatibility/autoload.php
/usr/local/ZendFramework-2.4.13/library/Zend/Stdlib/compatibility/autoload.php
</pre>

I did create a Google API Console project and client ID that I was capable to test successfully following that tutorial : https://developers.google.com/youtube/v3/quickstart/php

I did use the Oath2 client ID and Oath2 client secret in Private.php keeping my old youTube_developer key (I don know if it is still needed...) 
 

How can I upload a movie to YouTube/?
The doc does not seem up to date about it : http://wiki.helioviewer.org/wiki/Installing_Helioviewer.org#Youtube_support 
Can you help me with that one ? 

Best regards,
Pablo 
IAS

**Comment by ddialer** [comment]
Probably you downloaded HV without dependencies. Google SDK is linked in https://github.com/Helioviewer-Project/api/tree/master/src/Movie folder. 

You can just download Google SDK from here: https://github.com/google/google-api-php-client/tree/2bc00ec4e8fa1a5eec793d800fac339f30b730db and put it inside /src/Movie/GoogleSDK folder.

**Comment by MedocIAS** [comment]
All right thank you 

in the api directory the following will do 

<pre>
git submodule init
git submodule update
</pre>
