### ISSUE TITLE
Server/data unavailable in jhelioviewer

### ISSUE THREAD

**Issue by helioshk** [Helioviewer-Project/api#330]
On IAS I can't access data after 13 July. (on the helioviewer website it is ok though)
GSFC-beta is returning "connection refused" since a longer time, i think that is a different issue.
GSFC is good though.

**Comment by dgarciabriseno** [comment]
GSFC-Beta is available now on JHelioviewer

**Comment by dgarciabriseno** [comment]
Data is looking okay. Closing this.
