### ISSUE TITLE
GSFC AIA 171 data gap on 2023-03-29

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#332]
There is a data gap for AIA 171 starting at about 16:16 until midnight that day. The JP2 files are available, but not on the GSFC HV site. The other bandpasses seem unaffected.

**Comment by dgarciabriseno** [comment]
This gap is currently being filled in.

**Comment by bogdanni** [comment]
There is no rush, but this seems to take very long. 
https://helioviewer.org/jp2/AIA/2023/03/29/171/ still doesn't show files later than 16:16.

**Comment by dgarciabriseno** [comment]
They're there now.
