### ISSUE TITLE
JPX may not contain latest available frames

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#34]
When the `endTime` parameter of `getJPX` is later than the latest available frame, subsequent requests with the same `endTime` return the same JPX even though new frames may have become available in the meanwhile. I believe the decision whether to perform the merging step is based purely on the existence of the JPX file. I suggest to store the set of frame timestamps at the moment of JPX creation and, for later requests, compare with the current set and recreate the JPX if they differ.

The current behavior also prevents an optimization in JHV and, in general, the reduction of load layer operation latency.

**Comment by dgarciabriseno** [comment]
@bogdanni is this still an issue?

**Comment by bogdanni** [comment]
As far as I understand, nothing has been done for this. `Image_JPEG2000_HelioviewerJPXImage::__construct` simply just checks if the JSON file exists.

Imagine if I request in the morning frames from 0h to 24h of today. The files are created for the currently existing JP2s. If I request later that day exactly the same time interval, the same movie will be returned even though more files came through in the meanwhile.

**Comment by dgarciabriseno** [comment]
Committed to tag 3.3.2
