### ISSUE TITLE
getDataSources doesn't do what docs say it does

### ISSUE THREAD

**Issue by dgarciabriseno** [Helioviewer-Project/api#343]
option `verbose=true` makes the result only return SOHO and SDO. It's missing everything else that's returned when the option isn't sent.

option `enable` is supposed to specify specific observatories to return, this seems to be completely ignored.

**Comment by bogdanni** [comment]
This was a change from API v1 to v2. 

`enable` does turn on additional data sources, JHV was forced to use it. Here it is the current request:
`https://api.helioviewer.org/v2/getDataSources/?verbose=true&enable=[MLSO,TRACE,Hinode,Yohkoh,STEREO_A,STEREO_B,PROBA2,SOLO,GOES-R,IRIS]`

**Comment by dgarciabriseno** [comment]
I see. I was just looking through the docs and this is documented.

On a separate note, GSFC has GONG H-alpha now, could you enable that in JHelioviewer?

**Comment by bogdanni** [comment]
Is the GONG data prepared at ROB?
We are in the process of redoing all pipelines.

**Comment by dgarciabriseno** [comment]
Yes, it's the data prepared at ROB.

**Comment by bogdanni** [comment]
OK, request for GONG committed.
