### ISSUE TITLE
I found an XSS Vulnerability on the repo and on the main live site

### ISSUE THREAD

**Issue by S4lt5** [Helioviewer-Project/api#347]
I didn't see where to report a security vulnerability privately, so I will just mention here that I found a reflected XSS on the site and was able to craft a e.g. bit.ly link to pass to a helioviewer.org link that runs arbitrary javascript or changes UI elements to clickable links to where I want to users to click.

**Comment by dangarbri** [comment]
Could you reach out to us at helioviewerdevelopment@nasa.onmicrosoft.com?

**Comment by dgarciabriseno** [comment]
Fixed in 0774dacc4825ea793926c02d23e0febba7373fd0
