### ISSUE TITLE
'switchSources' column is missing in table 'movies'

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/api#36]
Hello, 
in my sql log I  can see :

<pre>
401 Query	INSERT INTO movies SET 
id  = NULL, timestamp  = NULL, reqStartDate  ="2018-03-02 03:02:12.000",
 reqEndDate  ="2018-03-03 03:02:12.000",
 reqObservationDate  ="2018-03-02 15:02:12.991",
 imageScale  = 2.420441,
 regionOfInterest  = PolygonFromText("POLYGON((-2040.43166184 -1126.71522964,2025.90901656 -1126.71522964,2025.90901656 1121.87434788,-2040.43166184 1121.87434788,-2040.43166184 -1126.71522964))"),
 maxFrames  = 300,
 watermark  = 1,
 dataSourceString  ="[SDO,AIA,304,1,100,0,60,1,2018-03-08T10:29:45.000Z]",
 dataSourceBitMask  = 1,
 eventSourceString  ="",
 eventsLabels  = 1,
 movieIcons  = 1,
 followViewport  = 0,
 scale  = 1,
 scaleType  ="earth",
scaleX  = 1003.000000,
 scaleY  = 985.000000,
 numLayers  = 1,
 queueNum  = 0,
 frameRate  = 15.000000,
 movieLength  = 0.000000,
 startDate  = NULL,
 endDate  = NULL,
 numFrames  = NULL,
 width  = NULL,
 height  = NULL,
 buildTimeStart  = NULL,
 buildTimeEnd  = NULL,
 size  = 0,
 switchSources  = 0
</pre>

I don't have any  switchSources column in [#api-directory]/install/helioviewer/db.py

Best regards, 
Pablo 
IAS

**Comment by dgarciabriseno** [comment]
This was fixed in commit:
commit c1f3f4cba79d7c7af0136b6708c701d2883666e0 (HEAD)
Author: Helioviewer-Kirill <kvorobyev@sesda.com>
Date:   Thu Apr 25 10:07:04 2019 -0400

    Fixed console based installer script
