### ISSUE TITLE
Unable to request video with info-helio-test.ias.u-psud.fr 

### ISSUE THREAD

**Issue by PabloA-dev-coder** [Helioviewer-Project/api#38]
Hello, 

queueMovie is ko on our side 

example: 
<pre>
https://inf-helio-test-api.ias.u-psud.fr/?action=queueMovie&imageScale=2.42044088&layers=[SDO,AIA,304,1,100,0,60,1,2018-03-08T10:29:45.000Z]& events=& eventsLabels=true& scale=true& scaleType=earth& scaleX=1003& scaleY=985& format=mp4& size=0& movieIcons=true& followViewport=0& reqObservationDate=2018-03-02T15:02:12.991Z& switchSources=false& x1=-2040.43166184& x2=2025.90901656& y1=-1126.71522964& y2=1121.87434788& startTime=2018-03-02T03:02:12.000Z& endTime=2018-03-03T03:02:12.000Z& frameRate=15
</pre>

the resque log : 
<pre>
Starting movie 2222Z
Error processing movie 2222Z
</pre>

Best regards, 
Pablo 
IAS

**Comment by MedocIAS** [comment]
Solved modifying the db 
mysql> alter table movies add column switchSources tinyint(2) NOT NULL DEFAULT '0' ;
Query OK, 4181 rows affected (0.45 sec)
Records: 4181  Duplicates: 0  Warnings: 0

Can you please let me know if the definition of this added column is right ?

**Comment by dgarciabriseno** [comment]
Helioviewer.org has this column set to:

tinyint(1) NOT NULL DEFAULT '0'

I will update db.py to reflect this.

**Comment by dgarciabriseno** [comment]
Released on tag 3.3.2
