### ISSUE TITLE
Suggestion for GetClosestImage

### ISSUE THREAD

**Issue by dzarro** [Helioviewer-Project/api#4]
I have a suggestion for _GetClosestImage_. Could it include the spacecraft, instrument, detector, and measurement fields in the JSON reponse output?

**Comment by wafels** [comment]
What is the use case for this?

**Comment by dzarro** [comment]
I guess it would be handy if one needed to pass the response to another 
routine for processing. Currently, the returned response below has no 
memory of where it came from. At the very least it, I think it should 
include the Source ID that generated it.


> { "id": 34205701, "date": "2014-01-02 00:00:02", "scale": 
> 0.58996068317702, "width": 4096, "height": 4096, "refPixelX": 2048.5, 
> "refPixelY": 2048.5, "sunCenterOffsetParams": [], "layeringOrder": 1 }

**Comment by wafels** [comment]
Do you want all the positioning information too?

**Comment by dzarro** [comment]
You mean like, image center in arcsecs? That would be useful if you can include it.

**Comment by wafels** [comment]
If you already have the sourceId to make the request, can't you package it along with the return from *GetClosestImage* by yourself?  Also, we have the *getDataSources* function that describes the observatory-instrument-detector-wavelength combination for that sourceId.  All the information is already available, and I think it is best not to duplicate the information.

**Comment by dzarro** [comment]
Good point. I'll incorporate it in my next release.

**Comment by wafels** [comment]
closed as answered.
