### ISSUE TITLE
LASCO C2 data lag

### ISSUE THREAD

**Issue by bogdanni** [Helioviewer-Project/api#409]
LASCO C2 data is currently available only up to Aug 2.

**Comment by mudhoney** [comment]
Thank you very much for letting us know, @bogdanni. 
We are currently looking into the issue and will provide an update when we fix it.

**Comment by wafels** [comment]
Some bad data on Aug. 2 caused the JP2 creation script to crash. I have re-started the script.

**Comment by bogdanni** [comment]
All seems well again, thanks for re-setting the wheels in motion.
