### ISSUE TITLE
Statistics page might be reporting the wrong summary numbers

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#44]
The numbers in the sentence at the top of https://api.helioviewer.org/statistics/ don't make sense when compared to the daily numbers.  For example when you divide the total number of observations by the number of days (14) you get a number ~35,000.  See the attachment.  None of the values in the histogram get to this number.  So either the totals are wrong, or the daily counts are wrong.  The screenshot and movies numbers look off too.  The JPX and embeds numbers may be wrong too.

![screen shot 2019-03-05 at 10 37 29 am](https://user-images.githubusercontent.com/983575/53817178-e71f1780-3f32-11e9-89fd-840dba6e0e6d.png)

**Comment by Helioviewer-Kirill** [comment]
The page is reporting the wrong number of days in the report. 
The report actually contains 28 days, the banner should read four weeks. This is now fixed.

**Comment by wafels** [comment]
Ah, well, that's an easy fix!  Thanks!
