### ISSUE TITLE
Coverage webpage not reacting to selections

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#48]
The coverage webpage the number of files held by the server at GSFC for each data source.  It is possible to change the bin size and time range

https://api.helioviewer.org/coverage/

but it seems that the webpage does not react to these changes.

**Comment by dgarciabriseno** [comment]
Fixed in 4eb4d80104b3434619433f589e51f095aaa08521 The problem was there was no validator for the getDataCoverageTimeline API. The function was using the _options variable which gets filled in by the validator.

**Comment by dgarciabriseno** [comment]
Fixed in 3.3.3
