### ISSUE TITLE
Check the coverage page and image timeline results

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#49]
The coverage page and image timeline show similar types of data.  They should be cross checked against each other, and against what is actually on the server.

**Comment by dgarciabriseno** [comment]
They're very close, but the image timeline returns a slightly lower number. Not sure if the discrepancy is worth looking into or not. I'd say it's okay.

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/94071409/210798656-080c1158-b974-48bf-b85f-48afaa1ed246.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/94071409/210798750-4ce9458b-d920-4c2c-bfbc-de4afad317be.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/94071409/210798808-986e0d7f-237f-4c49-a280-11a85427aa32.png">
<img width="235" alt="image" src="https://user-images.githubusercontent.com/94071409/210798986-2034b9c6-de72-4d13-8990-c6a6ff96db8a.png">

**Comment by wafels** [comment]
Why are they different? Are they always close?

**Comment by wafels** [comment]
It may be that the timeline statistics are created earlier in the day than the coverage statistics - not all the data has arrived yet.

**Comment by wafels** [comment]
Need to check also with the bokeh plots.
