### ISSUE TITLE
LASCO images are on the server but not accessible from helioviewer.org

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#54]
There is a large chunk of LASCO C2 and C3 images which are on the server and which are not accessible from helioviewer.org.  It looks as if the images are on the server but not in the database.  The missing images are in the timerange from 2015/02/03 until 2015/05/19.  This time range covers images from both C2 and C3.

KV suggested copying the images from the archive into the ingestion folder and re-running the ingestion script to get them inserted in to the DB.

**Comment by Helioviewer-Kirill** [comment]
Images within specified time range have been added to the database and are accessible on [helioviewer.org](helioviewer.org)
