### ISSUE TITLE
Missing STEREO EUVI data May 31, 2014 - June 2, 2014

### ISSUE THREAD

**Issue by takucera** [Helioviewer-Project/api#55]
Hi, I am trying to make a movie including STEREO EUVI data from the end of May to the start of June 2014. The data from May 31, 2014 - June 2, 2014 is not coming up from either IAS or GSFC in JHelioviewer. It does seem to exist in the STEREO data base.

**Comment by wafels** [comment]
These data are on the server now.  Please let me know if you can't access them.

**Comment by takucera** [comment]
Yes, I can access them with JHelioviewer. Thanks!
Terry
