### ISSUE TITLE
JHelioviewer Data 2 Days Old

### ISSUE THREAD

**Issue by simplio** [Helioviewer-Project/api#57]
I downloaded and installed the newest version. It can only see up to May 29. Here it is June 1. If I try to request it to download and display images from May 30 to May 31 it springs up a pop up saying no data on or after May 29. When will this be fixed?

**Comment by simplio** [comment]
![Screenshot 2021-06-01 060144](https://user-images.githubusercontent.com/53747770/120313898-400bc080-c2a0-11eb-8d3f-e49e7a59ce38.png)
I should have said AIA. Here is the screenshot of the error.

**Comment by bogdanni** [comment]
The AIA & HMI data data seems to have caught up. There are occasional computer glitches preventing the data distribution.
Thanks for keeping an eye on this. Closing.
