### ISSUE TITLE
MySQL server gone away

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#6]
There seem to be more instances of the error "MySQL server gone away" occurring.  This causes the data ingestion processes to crash.  One fix is to harden the ingestion process to catch this error.  However, the source of the error should also be tracked down - hopefully there is a consistent cause.

**Comment by wafels** [comment]
Seems like processes looking for "local" files (i.e. the local switch in downloader.py) are crashing more often.

**Comment by ddialer** [comment]
Applied new config values to handle longer mysql request to make sure mysql client not loosing connection. Will keep monitoring this issue for a few more days
