### ISSUE TITLE
Connection refused to GSFC server

### ISSUE THREAD

**Issue by angelos02** [Helioviewer-Project/api#71]
for a long time now, I have been unable to get data from the GSFC server. the connection is refused. This wasn't an issue before June, say. Below is the output from the log:
[jhv.2021-10-26T09-12-06.log](https://github.com/Helioviewer-Project/JHelioviewer-SWHV/files/7418430/jhv.2021-10-26T09-12-06.log)

**Comment by dgarciabriseno** [comment]
Yes, @wafels informed me there is a problem with the jpip server at GSFC so it has been disabled for a while. unfortunately I only have limited access to that server, so I can't see what's wrong yet.

**Comment by dgarciabriseno** [comment]
This is tentatively back online, now.
