### ISSUE TITLE
Use of SunPy in data ingestion

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#72]
The helioviewer back-end uses the SunPy Map object to get information on the JPEG2000 files being ingested. This is convenient because the SunPy Map object homogenizes the input from many different image sources.

However, as SunPy evolves, HV data ingestion has not kept pace. At present, HV data ingestion needs an old version of SunPy (v2.0.5). The data ingestion should be brought up to date with the current version of SunPy. This will also allow helioviewer to extract other useful metadata from the SunPy Map object that will be useful for future versions of helioviewer, for example, the observer position and the field of view of the data.

**Comment by dgarciabriseno** [comment]
Closing this. Currently using sunpy 4.1
