### ISSUE TITLE
Haven't been about to create HD videos  just low quality videos

### ISSUE THREAD

**Issue by wireeye** [Helioviewer-Project/api#75]
Good day to you, The problem I have noticed about Helioviewer is that It won't let you create a video in HD. Is this being worked on or will HD movies no longer be enabled? This is the message I get when I try to make a video in any HD mode. 
![Screenshot_2020-04-08 Helioviewer org](https://user-images.githubusercontent.com/35879228/78826348-5cb7ab80-79af-11ea-8ec7-eb17bc792bb6.png)

Thanks for your reply in advance.

**Comment by dgarciabriseno** [comment]
Looks like something wrong with what we're passing to FFMpeg when we create the video.
![image](https://user-images.githubusercontent.com/94071409/147689594-282301ba-af30-47c4-9e16-30494f0180b3.png)

**Comment by dgarciabriseno** [comment]
This is fixed on beta 7e5010cecd1a856fdbca161fc4509d70cbb45aaa
The ffmpeg command needed the -pix_fmt option for webm

**Comment by dgarciabriseno** [comment]
Fixed in 3.3.3
