### ISSUE TITLE
Dataframe keyError with Bokeh Plot Generation

### ISSUE THREAD

**Issue by nimatraore** [Helioviewer-Project/api#76]
When running the Bokeh plot generation, the script crashes with KeyError:
`##### Starting Bokeh Plot Generation Script #####
Thu 30 Dec 2021 03:31:56 PM CET
Starting SQL query for table data in hv database...
Querying completed in 84 seconds.
Preparing coverage plots...
Coverage plots completed.
Preparing histogram and cumulative distribution plots...
Histograms and cumulative distribution plots completed.
### Helioviewer Movies' Length histogram ###
Starting SQL query in movies table of hv database...
Query completed in 1 seconds.
Preparing histogram for movie lengths...
Histograms prepared.
### Stats for movies prepared per day ###
Starting SQL query in movies, screenshots, movies_jpx, statistics tables of hv database...
Query completed in 1 seconds.
Making time series of movies generated per day...
hv_movies
Jhv_movies
embed_service
hv_screenshots
Skipping empty table: hv_student
Time series completed.
Making histogram of movies generated per day...
Skipping empty table: hv_student
Histograms completed.
Making weekday frequency distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency distribution done
Making weekday frequency against weeknumber distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency against weeknumber distribution done.
Making weekly weekday distribution of movies generated per day...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/range.py", line 355, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hv_stats.py", line 1470, in <module>
    df_0['weeknumber'] = ((df_0['date']-df_0['date'][0]).dt.days/7).astype(int)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 990, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/range.py", line 357, in get_loc
    raise KeyError(key) from err
KeyError: 0
Copying Files to Web Directory api/docroot/statistics/bokeh/
Thu 30 Dec 2021 03:33:49 PM CET
Done!
#################################################
`
The dataframe df_0 above in the Traceback is empty.

**Comment by dgarciabriseno** [comment]
is df also empty? Line1445 is supposed to skip any empty datasets.

**Comment by dgarciabriseno** [comment]
Do you know which table it's crashing on? You can print key and title.

**Comment by nimatraore** [comment]
Yes I checked it: df is not empty but only df_0 is. And it seems related to Jhv_movies as shown in the Traceback below (with key and title printed):

##### Starting Bokeh Plot Generation Script #####
Fri 31 Dec 2021 11:20:09 AM CET
Starting SQL query for table data in hv database...
Querying completed in 70 seconds.
Preparing coverage plots...
Coverage plots completed.
Preparing histogram and cumulative distribution plots...
Histograms and cumulative distribution plots completed.
### Helioviewer Movies' Length histogram ###
Starting SQL query in movies table of hv database...
Query completed in 1 seconds.
Preparing histogram for movie lengths...
Histograms prepared.
### Stats for movies prepared per day ###
Starting SQL query in movies, screenshots, movies_jpx, statistics tables of hv database...
Query completed in 1 seconds.
Making time series of movies generated per day...
hv_movies
Jhv_movies
embed_service
hv_screenshots
Skipping empty table: hv_student
Time series completed.
Making histogram of movies generated per day...
Skipping empty table: hv_student
Histograms completed.
Making weekday frequency distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency distribution done
Making weekday frequency against weeknumber distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency against weeknumber distribution done.
Making weekly weekday distribution of movies generated per day...
key: hv_movies
title: Helioviewer.org Movies generated
df:
           id  count       date
0          1   26.0 2018-01-23
1         27   75.0 2018-01-24
2        102   11.0 2018-01-25
3        113   97.0 2018-01-26
4          0    0.0 2018-01-27
...      ...    ...        ...
1418  146150  124.0 2021-12-11
1419  146274  135.0 2021-12-12
1420  146409  119.0 2021-12-13
1421  146528  120.0 2021-12-14
1422  146648   61.0 2021-12-15

[1423 rows x 3 columns]
df_0:
     id  count       date
0    0      0 2018-01-27
1    0      0 2018-01-28
2    0      0 2020-02-27
3    0      0 2020-12-19
4    0      0 2020-12-20
5    0      0 2020-12-21
6    0      0 2020-12-22
7    0      0 2020-12-23
8    0      0 2020-12-24
9    0      0 2020-12-25
10   0      0 2020-12-26
11   0      0 2020-12-27
key: Jhv_movies
title: Helioviewer.org Screenshots generated
df:
      id  count       date
0     1  297.0 2021-12-28
1   298  447.0 2021-12-29
2   745  459.0 2021-12-30
3  1204    8.0 2021-12-31
df_0:
 Empty DataFrame
Columns: [id, count, date]
Index: []
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/range.py", line 355, in get_loc
    return self._range.index(new_key)
ValueError: 0 is not in range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "hv_stats.py", line 1473, in <module>
    df_0['weeknumber'] = ((df_0['date']-df_0['date'][0]).dt.days/7).astype(int)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 882, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/series.py", line 990, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/range.py", line 357, in get_loc
    raise KeyError(key) from err
KeyError: 0
Copying Files to Web Directory api/docroot/statistics/bokeh/
Fri 31 Dec 2021 11:21:43 AM CET
Done!
#################################################

**Comment by dgarciabriseno** [comment]
It's not the most elegant solution... but try cherry-picking this commit 1735b2bdba162684c4606c538eae93c75ee18373 

The df_0 table is generated by taking the date range from df, and filling in the blank spots with count = 0. It's crashing on your table where the range is 12-28 through 12-31 with no empty spots.

The patch here is to basically ignore it if there's no empty days.

**Comment by nimatraore** [comment]
Ok thank you! The cherry-picking worked pretty well but there is a small new error that appears. Below is the Traceback:

```
##### Starting Bokeh Plot Generation Script #####
Thu 06 Jan 2022 12:21:36 PM CET
Starting SQL query for table data in hv database...
Querying completed in 88 seconds.
Preparing coverage plots...
Coverage plots completed.
Preparing histogram and cumulative distribution plots...
Histograms and cumulative distribution plots completed.
### Helioviewer Movies' Length histogram ###
Starting SQL query in movies table of hv database...
Query completed in 1 seconds.
Preparing histogram for movie lengths...
Histograms prepared.
### Stats for movies prepared per day ###
Starting SQL query in movies, screenshots, movies_jpx, statistics tables of hv database...
Query completed in 1 seconds.
Making time series of movies generated per day...
hv_movies
Jhv_movies
embed_service
hv_screenshots
Skipping empty table: hv_student
Time series completed.
Making histogram of movies generated per day...
Skipping empty table: hv_student
Histograms completed.
Making weekday frequency distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency distribution done
Making weekday frequency against weeknumber distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency against weeknumber distribution done.
------------------Making weekly weekday distribution of movies generated per day...
Weekly weekday distribution done.
### Stats for movies per day done. ###
### Popularity plots ###
Making solar time popularity plots for helioviewer.org movies...
SDO popularity done in 40 seconds
SOHO popularity done in 10 seconds
STEREO_A popularity done in 5 seconds
STEREO_B popularity done in 3 seconds
Yohkoh popularity done in 0 seconds
PROBA2 popularity done in 1 seconds
Popularity plot done.
Making solar time popularity plots for Jhelioviewer movies...
SDO popularity done in 7 seconds
SOHO popularity done in 2 seconds
STEREO_A popularity done in 4 seconds
STEREO_B popularity done in 0 seconds
<=1 movies prepared with Yohkoh SXT AlMgMn
<=1 movies prepared with Yohkoh SXT thin-Al
<=1 movies prepared with Yohkoh SXT white-light
Skipping Yohkoh because it is empty
PROBA2 popularity done in 0 seconds
Popularity plot done.
Making data popularity plots for helioviewer movies...
SDO popularity done in 59 seconds
Popularity plot done.
ALL popularity plots done.
Service comparison...
Starting SQL query in movies and statistics table of hv database...
Query completed in 2 seconds.
Preparing plot for helioviewer services comparison...
Traceback (most recent call last):
  File "hv_stats.py", line 2201, in <module>
    p.line(y=[0,1.1], x=dt2ind(pd.Timestamp('2011/06/07')), line_width=1.5, line_dash='dotdash', color='red', alpha=1, legend_label= "failed eruption (2011/06/07)")
  File "hv_stats.py", line 2199, in dt2ind
    return frac.loc[frac['date']==dt].index[0]
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/indexes/base.py", line 4104, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
Copying Files to Web Directory api/docroot/statistics/bokeh/
Thu 06 Jan 2022 12:25:54 PM CET
Done!
#################################################
```

**Comment by dgarciabriseno** [comment]
Ok, try cherry-picking this one as well 1625256bc09b23bea6de784e962fc69b3de1cb7d
Another patch to ignore those lines if those dates are out of your data's time range.

**Comment by nimatraore** [comment]
I updated the code with the new cherry-picking, now there is a DataError raised by pivot_table:

```
##### Starting Bokeh Plot Generation Script #####
Tue 11 Jan 2022 12:40:28 PM CET
Starting SQL query for table data in hv database...
Querying completed in 88 seconds.
Preparing coverage plots...
Coverage plots completed.
Preparing histogram and cumulative distribution plots...
Histograms and cumulative distribution plots completed.
### Helioviewer Movies' Length histogram ###
Starting SQL query in movies table of hv database...
Query completed in 1 seconds.
Preparing histogram for movie lengths...
Histograms prepared.
### Stats for movies prepared per day ###
Starting SQL query in movies, screenshots, movies_jpx, statistics tables of hv database...
Query completed in 2 seconds.
Making time series of movies generated per day...
hv_movies
Jhv_movies
embed_service
hv_screenshots
Skipping empty table: hv_student
Time series completed.
Making histogram of movies generated per day...
Skipping empty table: hv_student
Histograms completed.
Making weekday frequency distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency distribution done
Making weekday frequency against weeknumber distribution of movies generated per day...
Skipping empty table: hv_student
Weekday frequency against weeknumber distribution done.
------------------Making weekly weekday distribution of movies generated per day...
Weekly weekday distribution done.
### Stats for movies per day done. ###
### Popularity plots ###
Making solar time popularity plots for helioviewer.org movies...
SDO popularity done in 37 seconds
SOHO popularity done in 11 seconds
STEREO_A popularity done in 5 seconds
STEREO_B popularity done in 3 seconds
Yohkoh popularity done in 0 seconds
PROBA2 popularity done in 1 seconds
Popularity plot done.
Making solar time popularity plots for Jhelioviewer movies...
SDO popularity done in 8 seconds
SOHO popularity done in 3 seconds
STEREO_A popularity done in 4 seconds
STEREO_B popularity done in 1 seconds
<=1 movies prepared with Yohkoh SXT AlMgMn
<=1 movies prepared with Yohkoh SXT thin-Al
<=1 movies prepared with Yohkoh SXT white-light
Skipping Yohkoh because it is empty
PROBA2 popularity done in 0 seconds
Popularity plot done.
Making data popularity plots for helioviewer movies...
SDO popularity done in 59 seconds
Popularity plot done.
ALL popularity plots done.
Service comparison...
Starting SQL query in movies and statistics table of hv database...
Query completed in 2 seconds.
Preparing plot for helioviewer services comparison...
Helioviewer service usage fraction plot done.
Starting SQL query in redis_stats table of hv database...
Query completed in 0 seconds
Traceback (most recent call last):
  File "hv_stats.py", line 2282, in <module>
    hv = hv.pivot_table(values='count', columns='action', index = ['date'])
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py", line 6836, in pivot_table
    observed=observed,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/reshape/pivot.py", line 112, in pivot_table
    agged = grouped.agg(aggfunc)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/generic.py", line 951, in aggregate
    result, how = self._aggregate(func, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/base.py", line 307, in _aggregate
    return self._try_aggregate_string_function(arg, *args, **kwargs), None
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/base.py", line 263, in _try_aggregate_string_function
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/groupby.py", line 1398, in mean
    numeric_only=numeric_only,
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/generic.py", line 1022, in _cython_agg_general
    how, alt=alt, numeric_only=numeric_only, min_count=min_count
  File "/usr/local/lib/python3.7/dist-packages/pandas/core/groupby/generic.py", line 1130, in _cython_agg_blocks
    raise DataError("No numeric types to aggregate")
pandas.core.base.DataError: No numeric types to aggregate
Copying Files to Web Directory api/docroot/statistics/bokeh/
Tue 11 Jan 2022 12:44:46 PM CET
Done!
#################################################
```

**Comment by dgarciabriseno** [comment]
can you print the hv['date'] table?

**Comment by nimatraore** [comment]
I have the hv table which is empty:

```
hv['date'] table :
 Series([], Name: date, dtype: datetime64[ns])

hv table :
 Empty DataFrame
Columns: [date, action, count]
```

**Comment by dgarciabriseno** [comment]
That's weird, when I run with an empty table it doesn't crash. Either way, add this commit onto it to ignore that too...
bc4d8c9f81344466f7203d5faa6dbceb4365e295

**Comment by nimatraore** [comment]
It's good, the script is running fine.

**Comment by nimatraore** [comment]
Thank you very much!
