### ISSUE TITLE
Mercury does not move like this 

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#79]
These movies:

https://helioviewer.org/?movieId=2YNN5
https://helioviewer.org/?movieId=DYNN5

shows Mercury moving in a very odd way. It does not move like this in reality. The motion of Mercury is wrong. The motion of Parker Solar Probe should also be checked.

**Comment by dgarciabriseno** [comment]
Identified that Image Magick does not like when we provide negative (off screen) coordinates. I can't really find any information about what behavior is expected if coordinates are negative, so the solution we've chosen here is to not draw the labels when the celestial body leaves the viewport.
This has been patched in beta c4a0be9627644e41c869d529c3d983b13ff6c020

**Comment by dgarciabriseno** [comment]
Fixed in 3.3.3
