### ISSUE TITLE
STEREO COR2 B images have spurious black bars in them

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#88]
The attached images show the appearance of black bars in the image. These are spurious, meaning that they are not in the original data. Images of the original data can be found here: https://stereo-ssc.nascom.nasa.gov/cgi-bin/images .

![Screen Shot 2021-10-01 at 10 36 12](https://user-images.githubusercontent.com/983575/135638389-7ab786c3-4d92-4e7b-a057-99a917f93eb7.png)
![Screen Shot 2021-10-01 at 10 35 59](https://user-images.githubusercontent.com/983575/135638393-5ec579b2-5f2c-4efa-8fc5-989718dc927e.png)
s.

Note also that images of earlier data appears to work ok. for example:
![Screen Shot 2021-10-01 at 10 41 42](https://user-images.githubusercontent.com/983575/135639249-f6edb202-72a1-4637-ba39-eb78c1c0bb5b.png)

**Comment by dgarciabriseno** [comment]
patched in e126bb9b0fdfd5d4dd85a6f1f85cea34427f38b5 by removing offset calculation. We'll have to keep an eye on this to make sure it was the right move.
