### ISSUE TITLE
Lack of HEK data recently

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#9]
There seems to be a real lack of HEK feature/event data recently.  A quick search of iSolSearch - http://www.lmsal.com/isolsearch - shows that there are many features and events available there, but there are almost none available via helioviewer.org or beta3.helioviewer.org.  Is the script that is collecting HEK data and creating the required images actually running?

Note - if this issue is in the wrong project, please let me know.

**Comment by wafels** [comment]
A user has pointed out that we have had no HEK data since 2015-12-18.  That is now two months.  Perhaps the HEK API has changed, and our requests for data have been crashing all the while?

**Comment by ddialer** [comment]
fixed

**Comment by wafels** [comment]
confirmed.
