### ISSUE TITLE
Hinode XRT "Any" feature not working as intended

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#93]
The "Any" selection for Hinode XRT is intended to mean "Any value of the filter wheel".  A user has reported that this selection is not working as intended.  For example, the filter selection "Al_med / open" is up to date (within a couple of weeks) but "Al_med / Any" gives an answer of a date some time in 2017.  It should have given the same result as "Al_med / open".

**Comment by wafels** [comment]
Moved to API repo since the problem lies there

**Comment by dgarciabriseno** [comment]
patched in 0484abc99bc7614164a754c60d3490053924ba92 on beta. I cherry-picked this onto the prod server for now since it's an important patch.

**Comment by dgarciabriseno** [comment]
Still need to repair existing data in the database.

**Comment by dgarciabriseno** [comment]
added another patch b0e19058048f5009b1fc5198a228b5ca3204c4cc that includes the sql query to patch the existing rows.

**Comment by dgarciabriseno** [comment]
Updated existing XRT rows, this looks like it's working now.
