### ISSUE TITLE
Movie recreation appears to be broken

### ISSUE THREAD

**Issue by wafels** [Helioviewer-Project/api#96]
I tried to recreate a movie, and the webpage reported the following error:

![screen shot 2017-09-12 at 1 55 06 pm](https://user-images.githubusercontent.com/983575/30340824-d1718504-97c1-11e7-899e-ddc003a4717d.png)

**Comment by dgarciabriseno** [comment]
Patched here 28713c07327fa23fcb7e470de9371b34530a3803

I also put this on the prod server and tested it. Now instead of reporting unknown status, it will report that the video is processing.
