### ISSUE TITLE
HMI data failing to load

### ISSUE THREAD

**Issue by Tom-Berger** [Helioviewer-Project/api#98]
Current and near-current data (~2022) seem to be available, but attempts to get data from 2017, 2015, 2014, and 2011 flare events failed with the error shown in the attached screen shot. 

Also, the error window does not text wrap and does not allow copying of text from the window (Mac OS 12.1).

JHV Version 4.3.1.10635

<img width="802" alt="screenshot_618" src="https://user-images.githubusercontent.com/36248958/152616515-10c84007-00ed-442f-b9e7-24a2bf9a01b0.png">

**Comment by ebuchlin** [comment]
We have deleted the database entries with no corresponding file on disk, and re-downloaded the corresponding data. There should be no large gaps left (when data are available) except mid-2015 and before mid-2012 (we're still filling these).

**Comment by dgarciabriseno** [comment]
It looks like this has been resolved. Closing.
